spring.profiles.active=h2

# Common
server.port=8080
jwt.secret=ReplaceThisWithASecureRandomSecretKeyOfAtLeast32Chars
jwt.expiration-ms=86400000

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
